reviews:
  path_filters:
    - "!**/*.css"
    - "!**/*.js"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.md"
    - "!**/*.json"
    - "!**/*.xml"
    - "!**/*.yml"
    - "!**/*.yaml"
    - "!**/*.txt"
    - "!.gitignore"
    - "!tests/**"
