<?php
/**
 * Dados compartilhados de países e idiomas para todo o plugin AlvoBot.
 *
 * Países: ISO 3166-1 alpha-2 => nome em português (249 entradas).
 * Idiomas: ISO 639-1 => label em português (183 entradas, populares primeiro).
 * Fonte: alvobot-app/frontend/src/shared/constants/countries.ts e languages.ts
 *
 * Usado por: Author Box, Essential Pages, Multi-Languages, Smart Internal Links, AI API.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Retorna lista completa de países (249) com nomes em português.
 * Chave = código ISO 3166-1 alpha-2, valor = nome em português.
 */
function alvobot_get_countries() {
	return array(
		'AF' => 'Afeganistão',
		'AX' => 'Ilhas Åland',
		'AL' => 'Albânia',
		'DZ' => 'Argélia',
		'AS' => 'Samoa Americana',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antártida',
		'AG' => 'Antígua e Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armênia',
		'AW' => 'Aruba',
		'AU' => 'Austrália',
		'AT' => 'Áustria',
		'AZ' => 'Azerbaijão',
		'BS' => 'Bahamas',
		'BH' => 'Bahrein',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Bielorrússia',
		'BE' => 'Bélgica',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermudas',
		'BT' => 'Butão',
		'BO' => 'Bolívia',
		'BQ' => 'Bonaire, Santo Eustáquio e Saba',
		'BA' => 'Bósnia e Herzegovina',
		'BW' => 'Botsuana',
		'BV' => 'Ilha Bouvet',
		'BR' => 'Brasil',
		'IO' => 'Território Britânico do Oceano Índico',
		'BN' => 'Brunei',
		'BG' => 'Bulgária',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'CV' => 'Cabo Verde',
		'KH' => 'Camboja',
		'CM' => 'Camarões',
		'CA' => 'Canadá',
		'KY' => 'Ilhas Cayman',
		'CF' => 'República Centro-Africana',
		'TD' => 'Chade',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Ilha Christmas',
		'CC' => 'Ilhas Cocos (Keeling)',
		'CO' => 'Colômbia',
		'KM' => 'Comores',
		'CG' => 'Congo',
		'CD' => 'República Democrática do Congo',
		'CK' => 'Ilhas Cook',
		'CR' => 'Costa Rica',
		'CI' => 'Costa do Marfim',
		'HR' => 'Croácia',
		'CU' => 'Cuba',
		'CW' => 'Curaçao',
		'CY' => 'Chipre',
		'CZ' => 'República Tcheca',
		'DK' => 'Dinamarca',
		'DJ' => 'Djibuti',
		'DM' => 'Dominica',
		'DO' => 'República Dominicana',
		'EC' => 'Equador',
		'EG' => 'Egito',
		'SV' => 'El Salvador',
		'GQ' => 'Guiné Equatorial',
		'ER' => 'Eritreia',
		'EE' => 'Estônia',
		'SZ' => 'Essuatíni',
		'ET' => 'Etiópia',
		'FK' => 'Ilhas Malvinas',
		'FO' => 'Ilhas Faroé',
		'FJ' => 'Fiji',
		'FI' => 'Finlândia',
		'FR' => 'França',
		'GF' => 'Guiana Francesa',
		'PF' => 'Polinésia Francesa',
		'TF' => 'Terras Austrais e Antárticas Francesas',
		'GA' => 'Gabão',
		'GM' => 'Gâmbia',
		'GE' => 'Geórgia',
		'DE' => 'Alemanha',
		'GH' => 'Gana',
		'GI' => 'Gibraltar',
		'GR' => 'Grécia',
		'GL' => 'Groenlândia',
		'GD' => 'Granada',
		'GP' => 'Guadalupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guiné',
		'GW' => 'Guiné-Bissau',
		'GY' => 'Guiana',
		'HT' => 'Haiti',
		'HM' => 'Ilha Heard e Ilhas McDonald',
		'VA' => 'Vaticano',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungria',
		'IS' => 'Islândia',
		'IN' => 'Índia',
		'ID' => 'Indonésia',
		'IR' => 'Irã',
		'IQ' => 'Iraque',
		'IE' => 'Irlanda',
		'IM' => 'Ilha de Man',
		'IL' => 'Israel',
		'IT' => 'Itália',
		'JM' => 'Jamaica',
		'JP' => 'Japão',
		'JE' => 'Jersey',
		'JO' => 'Jordânia',
		'KZ' => 'Cazaquistão',
		'KE' => 'Quênia',
		'KI' => 'Kiribati',
		'KP' => 'Coreia do Norte',
		'KR' => 'Coreia do Sul',
		'KW' => 'Kuwait',
		'KG' => 'Quirguistão',
		'LA' => 'Laos',
		'LV' => 'Letônia',
		'LB' => 'Líbano',
		'LS' => 'Lesoto',
		'LR' => 'Libéria',
		'LY' => 'Líbia',
		'LI' => 'Liechtenstein',
		'LT' => 'Lituânia',
		'LU' => 'Luxemburgo',
		'MO' => 'Macau',
		'MG' => 'Madagascar',
		'MW' => 'Malaui',
		'MY' => 'Malásia',
		'MV' => 'Maldivas',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Ilhas Marshall',
		'MQ' => 'Martinica',
		'MR' => 'Mauritânia',
		'MU' => 'Maurício',
		'YT' => 'Mayotte',
		'MX' => 'México',
		'FM' => 'Micronésia',
		'MD' => 'Moldávia',
		'MC' => 'Mônaco',
		'MN' => 'Mongólia',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MA' => 'Marrocos',
		'MZ' => 'Moçambique',
		'MM' => 'Mianmar',
		'NA' => 'Namíbia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Países Baixos',
		'NC' => 'Nova Caledônia',
		'NZ' => 'Nova Zelândia',
		'NI' => 'Nicarágua',
		'NE' => 'Níger',
		'NG' => 'Nigéria',
		'NU' => 'Niue',
		'NF' => 'Ilha Norfolk',
		'MK' => 'Macedônia do Norte',
		'MP' => 'Ilhas Marianas do Norte',
		'NO' => 'Noruega',
		'OM' => 'Omã',
		'PK' => 'Paquistão',
		'PW' => 'Palau',
		'PS' => 'Palestina',
		'PA' => 'Panamá',
		'PG' => 'Papua-Nova Guiné',
		'PY' => 'Paraguai',
		'PE' => 'Peru',
		'PH' => 'Filipinas',
		'PN' => 'Ilhas Pitcairn',
		'PL' => 'Polônia',
		'PT' => 'Portugal',
		'PR' => 'Porto Rico',
		'QA' => 'Catar',
		'RE' => 'Reunião',
		'RO' => 'Romênia',
		'RU' => 'Rússia',
		'RW' => 'Ruanda',
		'BL' => 'São Bartolomeu',
		'SH' => 'Santa Helena',
		'KN' => 'São Cristóvão e Névis',
		'LC' => 'Santa Lúcia',
		'MF' => 'São Martinho',
		'PM' => 'São Pedro e Miquelão',
		'VC' => 'São Vicente e Granadinas',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'São Tomé e Príncipe',
		'SA' => 'Arábia Saudita',
		'SN' => 'Senegal',
		'RS' => 'Sérvia',
		'SC' => 'Seicheles',
		'SL' => 'Serra Leoa',
		'SG' => 'Singapura',
		'SX' => 'São Martinho (Países Baixos)',
		'SK' => 'Eslováquia',
		'SI' => 'Eslovênia',
		'SB' => 'Ilhas Salomão',
		'SO' => 'Somália',
		'ZA' => 'África do Sul',
		'GS' => 'Geórgia do Sul',
		'SS' => 'Sudão do Sul',
		'ES' => 'Espanha',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudão',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard e Jan Mayen',
		'SE' => 'Suécia',
		'CH' => 'Suíça',
		'SY' => 'Síria',
		'TW' => 'Taiwan',
		'TJ' => 'Tadjiquistão',
		'TZ' => 'Tanzânia',
		'TH' => 'Tailândia',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad e Tobago',
		'TN' => 'Tunísia',
		'TR' => 'Turquia',
		'TM' => 'Turcomenistão',
		'TC' => 'Ilhas Turcas e Caicos',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UA' => 'Ucrânia',
		'AE' => 'Emirados Árabes Unidos',
		'GB' => 'Reino Unido',
		'US' => 'Estados Unidos',
		'UM' => 'Ilhas Menores Distantes dos EUA',
		'UY' => 'Uruguai',
		'UZ' => 'Uzbequistão',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'VN' => 'Vietnã',
		'VG' => 'Ilhas Virgens Britânicas',
		'VI' => 'Ilhas Virgens Americanas',
		'WF' => 'Wallis e Futuna',
		'EH' => 'Saara Ocidental',
		'YE' => 'Iêmen',
		'ZM' => 'Zâmbia',
		'ZW' => 'Zimbábue',
	);
}

/**
 * Retorna lista completa de idiomas ISO 639-1 (183) com labels em português.
 * Idiomas populares aparecem primeiro para facilitar a seleção.
 * Chave = código ISO 639-1, valor = nome em português.
 */
function alvobot_get_languages() {
	return array(
		'pt' => 'Português',
		'en' => 'Inglês',
		'es' => 'Espanhol',
		'fr' => 'Francês',
		'de' => 'Alemão',
		'it' => 'Italiano',
		'nl' => 'Holandês',
		'ja' => 'Japonês',
		'zh' => 'Chinês',
		'ko' => 'Coreano',
		'ru' => 'Russo',
		'ar' => 'Árabe',
		'hi' => 'Hindi',
		'tr' => 'Turco',
		'pl' => 'Polonês',
		'sv' => 'Sueco',
		'da' => 'Dinamarquês',
		'nb' => 'Norueguês Bokmål',
		'fi' => 'Finlandês',
		'el' => 'Grego',
		'cs' => 'Tcheco',
		'ro' => 'Romeno',
		'hu' => 'Húngaro',
		'th' => 'Tailandês',
		'vi' => 'Vietnamita',
		'id' => 'Indonésio',
		'ms' => 'Malaio',
		'he' => 'Hebraico',
		'uk' => 'Ucraniano',
		'bg' => 'Búlgaro',
		'hr' => 'Croata',
		'sk' => 'Eslovaco',
		'sl' => 'Esloveno',
		'et' => 'Estoniano',
		'lv' => 'Letão',
		'lt' => 'Lituano',
		'sr' => 'Sérvio',
		'bs' => 'Bósnio',
		'sq' => 'Albanês',
		'mk' => 'Macedônio',
		'ka' => 'Georgiano',
		'hy' => 'Armênio',
		'az' => 'Azerbaijano',
		'kk' => 'Cazaque',
		'uz' => 'Uzbeque',
		'fa' => 'Persa',
		'ur' => 'Urdu',
		'bn' => 'Bengali',
		'ta' => 'Tâmil',
		'te' => 'Telugu',
		'ml' => 'Malaiala',
		'kn' => 'Canarês',
		'mr' => 'Marata',
		'gu' => 'Guzerate',
		'pa' => 'Panjabi',
		'ne' => 'Nepalês',
		'si' => 'Cingalês',
		'my' => 'Birmanês',
		'km' => 'Khmer',
		'lo' => 'Laosiano',
		'mn' => 'Mongol',
		'sw' => 'Suaíli',
		'am' => 'Amárico',
		'yo' => 'Iorubá',
		'ig' => 'Igbo',
		'ha' => 'Hauçá',
		'zu' => 'Zulu',
		'xh' => 'Xhosa',
		'af' => 'Africâner',
		'tl' => 'Tagalo',
		'mt' => 'Maltês',
		'is' => 'Islandês',
		'ga' => 'Irlandês',
		'cy' => 'Galês',
		'gl' => 'Galego',
		'ca' => 'Catalão',
		'eu' => 'Basco',
		'la' => 'Latim',
		'eo' => 'Esperanto',
		'gn' => 'Guarani',
		'qu' => 'Quíchua',
		'ay' => 'Aimará',
		'aa' => 'Afar',
		'ab' => 'Abecásio',
		'ae' => 'Avéstico',
		'ak' => 'Akan',
		'an' => 'Aragonês',
		'as' => 'Assamês',
		'av' => 'Avar',
		'ba' => 'Bashkir',
		'be' => 'Bielorrusso',
		'bi' => 'Bislama',
		'bm' => 'Bambara',
		'bo' => 'Tibetano',
		'br' => 'Bretão',
		'ce' => 'Checheno',
		'ch' => 'Chamorro',
		'co' => 'Corso',
		'cr' => 'Cree',
		'cu' => 'Eslavo Eclesiástico',
		'cv' => 'Chuvash',
		'dv' => 'Divehi',
		'dz' => 'Dzonga',
		'ee' => 'Ewe',
		'ff' => 'Fula',
		'fj' => 'Fijiano',
		'fo' => 'Feroês',
		'fy' => 'Frísio Ocidental',
		'gd' => 'Gaélico Escocês',
		'gv' => 'Manx',
		'ho' => 'Hiri Motu',
		'ht' => 'Haitiano',
		'hz' => 'Herero',
		'ia' => 'Interlíngua',
		'ie' => 'Interlíngue',
		'ii' => 'Yi de Sichuan',
		'ik' => 'Inupiaque',
		'io' => 'Ido',
		'iu' => 'Inuktitut',
		'jv' => 'Javanês',
		'kg' => 'Congolês',
		'ki' => 'Quicuio',
		'kj' => 'Cuanhama',
		'kl' => 'Groenlandês',
		'kr' => 'Canúri',
		'ks' => 'Caxemira',
		'ku' => 'Curdo',
		'kv' => 'Komi',
		'kw' => 'Córnico',
		'ky' => 'Quirguiz',
		'lb' => 'Luxemburguês',
		'lg' => 'Luganda',
		'li' => 'Limburguês',
		'ln' => 'Lingala',
		'lu' => 'Luba-Catanga',
		'mg' => 'Malgaxe',
		'mh' => 'Marshalês',
		'mi' => 'Maori',
		'na' => 'Nauruano',
		'nd' => 'Ndebele do Norte',
		'ng' => 'Ndonga',
		'nn' => 'Norueguês Nynorsk',
		'no' => 'Norueguês',
		'nr' => 'Ndebele do Sul',
		'nv' => 'Navajo',
		'ny' => 'Chichewa',
		'oc' => 'Occitano',
		'oj' => 'Ojibwa',
		'om' => 'Oromo',
		'or' => 'Oriá',
		'os' => 'Osseta',
		'pi' => 'Páli',
		'ps' => 'Pashto',
		'rm' => 'Romanche',
		'rn' => 'Rundi',
		'rw' => 'Ruanda',
		'sa' => 'Sânscrito',
		'sc' => 'Sardo',
		'sd' => 'Sindi',
		'se' => 'Sami do Norte',
		'sg' => 'Sango',
		'sm' => 'Samoano',
		'sn' => 'Shona',
		'so' => 'Somali',
		'ss' => 'Suázi',
		'st' => 'Soto do Sul',
		'su' => 'Sundanês',
		'tg' => 'Tadjique',
		'ti' => 'Tigrínia',
		'tk' => 'Turcomano',
		'tn' => 'Tswana',
		'to' => 'Tonganês',
		'ts' => 'Tsonga',
		'tt' => 'Tártaro',
		'tw' => 'Twi',
		'ty' => 'Taitiano',
		'ug' => 'Uigur',
		've' => 'Venda',
		'vo' => 'Volapuque',
		'wa' => 'Valão',
		'wo' => 'Uolofe',
		'yi' => 'Iídiche',
		'za' => 'Zhuang',
	);
}

/**
 * Retorna nome nativo do idioma a partir do código ISO 639-1.
 * Cobertura completa: todos os 183 idiomas ISO 639-1.
 * Ex: 'pt' => 'Português', 'en' => 'English', 'ja' => '日本語'
 */
function alvobot_get_language_native_name( $lang_code ) {
	$native_names = array(
		// Populares
		'pt' => 'Português',
		'en' => 'English',
		'es' => 'Español',
		'fr' => 'Français',
		'de' => 'Deutsch',
		'it' => 'Italiano',
		'nl' => 'Nederlands',
		'ja' => '日本語',
		'zh' => '中文',
		'ko' => '한국어',
		'ru' => 'Русский',
		'ar' => 'العربية',
		'hi' => 'हिन्दी',
		'tr' => 'Türkçe',
		'pl' => 'Polski',
		'sv' => 'Svenska',
		'da' => 'Dansk',
		'nb' => 'Norsk Bokmål',
		'fi' => 'Suomi',
		'el' => 'Ελληνικά',
		'cs' => 'Čeština',
		'ro' => 'Română',
		'hu' => 'Magyar',
		'th' => 'ไทย',
		'vi' => 'Tiếng Việt',
		'id' => 'Bahasa Indonesia',
		'ms' => 'Bahasa Melayu',
		'he' => 'עברית',
		'uk' => 'Українська',
		'bg' => 'Български',
		'hr' => 'Hrvatski',
		'sk' => 'Slovenčina',
		'sl' => 'Slovenščina',
		'et' => 'Eesti',
		'lv' => 'Latviešu',
		'lt' => 'Lietuvių',
		'sr' => 'Српски',
		'bs' => 'Bosanski',
		'sq' => 'Shqip',
		'mk' => 'Македонски',
		'ka' => 'ქართული',
		'hy' => 'Հայերեն',
		'az' => 'Azərbaycan',
		'kk' => 'Қазақша',
		'uz' => 'Oʻzbek',
		'fa' => 'فارسی',
		'ur' => 'اردو',
		'bn' => 'বাংলা',
		'ta' => 'தமிழ்',
		'te' => 'తెలుగు',
		'ml' => 'മലയാളം',
		'kn' => 'ಕನ್ನಡ',
		'mr' => 'मराठी',
		'gu' => 'ગુજરાતી',
		'pa' => 'ਪੰਜਾਬੀ',
		'ne' => 'नेपाली',
		'si' => 'සිංහල',
		'my' => 'မြန်မာ',
		'km' => 'ខ្មែរ',
		'lo' => 'ລາວ',
		'mn' => 'Монгол',
		'sw' => 'Kiswahili',
		'am' => 'አማርኛ',
		'yo' => 'Yorùbá',
		'ig' => 'Igbo',
		'ha' => 'Hausa',
		'zu' => 'isiZulu',
		'xh' => 'isiXhosa',
		'af' => 'Afrikaans',
		'tl' => 'Tagalog',
		'mt' => 'Malti',
		'is' => 'Íslenska',
		'ga' => 'Gaeilge',
		'cy' => 'Cymraeg',
		'gl' => 'Galego',
		'ca' => 'Català',
		'eu' => 'Euskara',
		'la' => 'Latina',
		'eo' => 'Esperanto',
		'gn' => "Avañe'ẽ",
		'qu' => 'Runa Simi',
		'ay' => 'Aymar Aru',
		// Menos comuns (ordem alfabética por código)
		'aa' => 'Afaraf',
		'ab' => 'Аԥсуа',
		'ae' => 'Avesta',
		'ak' => 'Akan',
		'an' => 'Aragonés',
		'as' => 'অসমীয়া',
		'av' => 'Авар',
		'ba' => 'Башҡорт',
		'be' => 'Беларуская',
		'bi' => 'Bislama',
		'bm' => 'Bamanankan',
		'bo' => 'བོད་ཡིག',
		'br' => 'Brezhoneg',
		'ce' => 'Нохчийн',
		'ch' => 'Chamoru',
		'co' => 'Corsu',
		'cr' => 'ᓀᐦᐃᔭᐍᐏᐣ',
		'cu' => 'Словѣньскъ',
		'cv' => 'Чӑваш',
		'dv' => 'ދިވެހި',
		'dz' => 'རྫོང་ཁ',
		'ee' => 'Eʋegbe',
		'ff' => 'Fulfulde',
		'fj' => 'Vosa Vakaviti',
		'fo' => 'Føroyskt',
		'fy' => 'Frysk',
		'gd' => 'Gàidhlig',
		'gv' => 'Gaelg',
		'ho' => 'Hiri Motu',
		'ht' => 'Kreyòl Ayisyen',
		'hz' => 'Otjiherero',
		'ia' => 'Interlingua',
		'ie' => 'Interlingue',
		'ii' => 'ꆈꌠꉙ',
		'ik' => 'Iñupiaq',
		'io' => 'Ido',
		'iu' => 'ᐃᓄᒃᑎᑐᑦ',
		'jv' => 'Basa Jawa',
		'kg' => 'Kikongo',
		'ki' => 'Gĩkũyũ',
		'kj' => 'Kuanyama',
		'kl' => 'Kalaallisut',
		'kr' => 'Kanuri',
		'ks' => 'कश्मीरी',
		'ku' => 'Kurdî',
		'kv' => 'Коми',
		'kw' => 'Kernewek',
		'ky' => 'Кыргызча',
		'lb' => 'Lëtzebuergesch',
		'lg' => 'Luganda',
		'li' => 'Limburgs',
		'ln' => 'Lingála',
		'lu' => 'Kiluba',
		'mg' => 'Malagasy',
		'mh' => 'Kajin M̧ajeḷ',
		'mi' => 'Te Reo Māori',
		'na' => 'Dorerin Naoero',
		'nd' => 'isiNdebele (North)',
		'ng' => 'Owambo',
		'nn' => 'Norsk Nynorsk',
		'no' => 'Norsk',
		'nr' => 'isiNdebele (South)',
		'nv' => 'Diné Bizaad',
		'ny' => 'Chichewa',
		'oc' => 'Occitan',
		'oj' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
		'om' => 'Afaan Oromoo',
		'or' => 'ଓଡ଼ିଆ',
		'os' => 'Ирон',
		'pi' => 'पालि',
		'ps' => 'پښتو',
		'rm' => 'Rumantsch',
		'rn' => 'Ikirundi',
		'rw' => 'Ikinyarwanda',
		'sa' => 'संस्कृतम्',
		'sc' => 'Sardu',
		'sd' => 'سنڌي',
		'se' => 'Davvisámegiella',
		'sg' => 'Sängö',
		'sm' => 'Gagana Sāmoa',
		'sn' => 'ChiShona',
		'so' => 'Soomaali',
		'ss' => 'SiSwati',
		'st' => 'Sesotho',
		'su' => 'Basa Sunda',
		'tg' => 'Тоҷикӣ',
		'ti' => 'ትግርኛ',
		'tk' => 'Türkmen',
		'tn' => 'Setswana',
		'to' => 'Lea Fakatonga',
		'ts' => 'Xitsonga',
		'tt' => 'Татар',
		'tw' => 'Twi',
		'ty' => 'Reo Tahiti',
		'ug' => 'ئۇيغۇرچە',
		've' => 'Tshivenḓa',
		'vo' => 'Volapük',
		'wa' => 'Walon',
		'wo' => 'Wolof',
		'yi' => 'ייִדיש',
		'za' => 'Saɯ Cueŋƅ',
	);

	return isset( $native_names[ $lang_code ] ) ? $native_names[ $lang_code ] : $lang_code;
}

/**
 * Retorna emoji de bandeira representativa do idioma.
 * Cobertura completa: todos os 183 idiomas ISO 639-1.
 * Mapeia código ISO 639-1 para a bandeira do país mais representativo.
 */
function alvobot_get_language_flag( $lang_code ) {
	$flags = array(
		// Populares
		'pt' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xB7", // 🇧🇷 Brasil
		'en' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8", // 🇺🇸 EUA
		'es' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8", // 🇪🇸 Espanha
		'fr' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7", // 🇫🇷 França
		'de' => "\xF0\x9F\x87\xA9\xF0\x9F\x87\xAA", // 🇩🇪 Alemanha
		'it' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB9", // 🇮🇹 Itália
		'nl' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB1", // 🇳🇱 Países Baixos
		'ja' => "\xF0\x9F\x87\xAF\xF0\x9F\x87\xB5", // 🇯🇵 Japão
		'zh' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB3", // 🇨🇳 China
		'ko' => "\xF0\x9F\x87\xB0\xF0\x9F\x87\xB7", // 🇰🇷 Coreia do Sul
		'ru' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia
		'ar' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xA6", // 🇸🇦 Arábia Saudita
		'hi' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'tr' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xB7", // 🇹🇷 Turquia
		'pl' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xB1", // 🇵🇱 Polônia
		'sv' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xAA", // 🇸🇪 Suécia
		'da' => "\xF0\x9F\x87\xA9\xF0\x9F\x87\xB0", // 🇩🇰 Dinamarca
		'nb' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB4", // 🇳🇴 Noruega
		'fi' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xAE", // 🇫🇮 Finlândia
		'el' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xB7", // 🇬🇷 Grécia
		'cs' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xBF", // 🇨🇿 República Tcheca
		'ro' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xB4", // 🇷🇴 Romênia
		'hu' => "\xF0\x9F\x87\xAD\xF0\x9F\x87\xBA", // 🇭🇺 Hungria
		'th' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xAD", // 🇹🇭 Tailândia
		'vi' => "\xF0\x9F\x87\xBB\xF0\x9F\x87\xB3", // 🇻🇳 Vietnã
		'id' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xA9", // 🇮🇩 Indonésia
		'ms' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xBE", // 🇲🇾 Malásia
		'he' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB1", // 🇮🇱 Israel
		'uk' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xA6", // 🇺🇦 Ucrânia
		'bg' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xAC", // 🇧🇬 Bulgária
		'hr' => "\xF0\x9F\x87\xAD\xF0\x9F\x87\xB7", // 🇭🇷 Croácia
		'sk' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xB0", // 🇸🇰 Eslováquia
		'sl' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xAE", // 🇸🇮 Eslovênia
		'et' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xAA", // 🇪🇪 Estônia
		'lv' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xBB", // 🇱🇻 Letônia
		'lt' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xB9", // 🇱🇹 Lituânia
		'sr' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xB8", // 🇷🇸 Sérvia
		'bs' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xA6", // 🇧🇦 Bósnia
		'sq' => "\xF0\x9F\x87\xA6\xF0\x9F\x87\xB1", // 🇦🇱 Albânia
		'mk' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xB0", // 🇲🇰 Macedônia do Norte
		'ka' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xAA", // 🇬🇪 Geórgia
		'hy' => "\xF0\x9F\x87\xA6\xF0\x9F\x87\xB2", // 🇦🇲 Armênia
		'az' => "\xF0\x9F\x87\xA6\xF0\x9F\x87\xBF", // 🇦🇿 Azerbaijão
		'kk' => "\xF0\x9F\x87\xB0\xF0\x9F\x87\xBF", // 🇰🇿 Cazaquistão
		'uz' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xBF", // 🇺🇿 Uzbequistão
		'fa' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB7", // 🇮🇷 Irã
		'ur' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xB0", // 🇵🇰 Paquistão
		'bn' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xA9", // 🇧🇩 Bangladesh
		'ta' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'te' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'ml' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'kn' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'mr' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'gu' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'pa' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'ne' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB5", // 🇳🇵 Nepal
		'si' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xB0", // 🇱🇰 Sri Lanka
		'my' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xB2", // 🇲🇲 Mianmar
		'km' => "\xF0\x9F\x87\xB0\xF0\x9F\x87\xAD", // 🇰🇭 Camboja
		'lo' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xA6", // 🇱🇦 Laos
		'mn' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xB3", // 🇲🇳 Mongólia
		'sw' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xBF", // 🇹🇿 Tanzânia
		'am' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB9", // 🇪🇹 Etiópia
		'yo' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xAC", // 🇳🇬 Nigéria
		'ig' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xAC", // 🇳🇬 Nigéria
		'ha' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xAC", // 🇳🇬 Nigéria
		'zu' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'xh' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'af' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'tl' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xAD", // 🇵🇭 Filipinas
		'mt' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xB9", // 🇲🇹 Malta
		'is' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB8", // 🇮🇸 Islândia
		'ga' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xAA", // 🇮🇪 Irlanda
		'cy' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xA7", // 🇬🇧 Reino Unido (Gales)
		'gl' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8", // 🇪🇸 Espanha (Galiza)
		'ca' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8", // 🇪🇸 Espanha (Catalunha)
		'eu' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8", // 🇪🇸 Espanha (País Basco)
		'la' => "\xF0\x9F\x87\xBB\xF0\x9F\x87\xA6", // 🇻🇦 Vaticano
		'eo' => "\xF0\x9F\x8C\x8D",                   // 🌍 Global
		'gn' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xBE", // 🇵🇾 Paraguai
		'qu' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xAA", // 🇵🇪 Peru
		'ay' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xB4", // 🇧🇴 Bolívia
		// Menos comuns
		'aa' => "\xF0\x9F\x87\xA9\xF0\x9F\x87\xAF", // 🇩🇯 Djibuti
		'ab' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xAA", // 🇬🇪 Geórgia (Abecásia)
		'ae' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB7", // 🇮🇷 Irã
		'ak' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xAD", // 🇬🇭 Gana
		'an' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8", // 🇪🇸 Espanha (Aragão)
		'as' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'av' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Daguestão)
		'ba' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Bascortostão)
		'be' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xBE", // 🇧🇾 Bielorrússia
		'bi' => "\xF0\x9F\x87\xBB\xF0\x9F\x87\xBA", // 🇻🇺 Vanuatu
		'bm' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xB1", // 🇲🇱 Mali
		'bo' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB3", // 🇨🇳 China (Tibete)
		'br' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7", // 🇫🇷 França (Bretanha)
		'ce' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Chechênia)
		'ch' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xBA", // 🇬🇺 Guam
		'co' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7", // 🇫🇷 França (Córsega)
		'cr' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA6", // 🇨🇦 Canadá
		'cu' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xAC", // 🇧🇬 Bulgária
		'cv' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Chuvássia)
		'dv' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xBB", // 🇲🇻 Maldivas
		'dz' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xB9", // 🇧🇹 Butão
		'ee' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xAD", // 🇬🇭 Gana
		'ff' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xB3", // 🇸🇳 Senegal
		'fj' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xAF", // 🇫🇯 Fiji
		'fo' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB4", // 🇫🇴 Ilhas Faroé
		'fy' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB1", // 🇳🇱 Países Baixos (Frísia)
		'gd' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xA7", // 🇬🇧 Reino Unido (Escócia)
		'gv' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB2", // 🇮🇲 Ilha de Man
		'ho' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xAC", // 🇵🇬 Papua-Nova Guiné
		'ht' => "\xF0\x9F\x87\xAD\xF0\x9F\x87\xB9", // 🇭🇹 Haiti
		'hz' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xA6", // 🇳🇦 Namíbia
		'ia' => "\xF0\x9F\x8C\x90",                   // 🌐 Global
		'ie' => "\xF0\x9F\x8C\x90",                   // 🌐 Global
		'ii' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB3", // 🇨🇳 China (Sichuan)
		'ik' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8", // 🇺🇸 EUA (Alaska)
		'io' => "\xF0\x9F\x8C\x90",                   // 🌐 Global
		'iu' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA6", // 🇨🇦 Canadá
		'jv' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xA9", // 🇮🇩 Indonésia (Java)
		'kg' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA9", // 🇨🇩 Congo
		'ki' => "\xF0\x9F\x87\xB0\xF0\x9F\x87\xAA", // 🇰🇪 Quênia
		'kj' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xA6", // 🇳🇦 Namíbia
		'kl' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xB1", // 🇬🇱 Groenlândia
		'kr' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xAC", // 🇳🇬 Nigéria
		'ks' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia (Caxemira)
		'ku' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB6", // 🇮🇶 Iraque
		'kv' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Komi)
		'kw' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xA7", // 🇬🇧 Reino Unido (Cornualha)
		'ky' => "\xF0\x9F\x87\xB0\xF0\x9F\x87\xAC", // 🇰🇬 Quirguistão
		'lb' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xBA", // 🇱🇺 Luxemburgo
		'lg' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xAC", // 🇺🇬 Uganda
		'li' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB1", // 🇳🇱 Países Baixos (Limburgo)
		'ln' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA9", // 🇨🇩 Congo
		'lu' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA9", // 🇨🇩 Congo
		'mg' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xAC", // 🇲🇬 Madagascar
		'mh' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xAD", // 🇲🇭 Ilhas Marshall
		'mi' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xBF", // 🇳🇿 Nova Zelândia
		'na' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB7", // 🇳🇷 Nauru
		'nd' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xBC", // 🇿🇼 Zimbábue
		'ng' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xA6", // 🇳🇦 Namíbia
		'nn' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB4", // 🇳🇴 Noruega
		'no' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB4", // 🇳🇴 Noruega
		'nr' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'nv' => "\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8", // 🇺🇸 EUA
		'ny' => "\xF0\x9F\x87\xB2\xF0\x9F\x87\xBC", // 🇲🇼 Malaui
		'oc' => "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7", // 🇫🇷 França (Occitânia)
		'oj' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA6", // 🇨🇦 Canadá
		'om' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB9", // 🇪🇹 Etiópia
		'or' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia (Odisha)
		'os' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Ossétia)
		'pi' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'ps' => "\xF0\x9F\x87\xA6\xF0\x9F\x87\xAB", // 🇦🇫 Afeganistão
		'rm' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xAD", // 🇨🇭 Suíça
		'rn' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xAE", // 🇧🇮 Burundi
		'rw' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBC", // 🇷🇼 Ruanda
		'sa' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB3", // 🇮🇳 Índia
		'sc' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB9", // 🇮🇹 Itália (Sardenha)
		'sd' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xB0", // 🇵🇰 Paquistão
		'se' => "\xF0\x9F\x87\xB3\xF0\x9F\x87\xB4", // 🇳🇴 Noruega (Sápmi)
		'sg' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xAB", // 🇨🇫 República Centro-Africana
		'sm' => "\xF0\x9F\x87\xBC\xF0\x9F\x87\xB8", // 🇼🇸 Samoa
		'sn' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xBC", // 🇿🇼 Zimbábue
		'so' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xB4", // 🇸🇴 Somália
		'ss' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xBF", // 🇸🇿 Essuatíni
		'st' => "\xF0\x9F\x87\xB1\xF0\x9F\x87\xB8", // 🇱🇸 Lesoto
		'su' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xA9", // 🇮🇩 Indonésia (Sundanês)
		'tg' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xAF", // 🇹🇯 Tadjiquistão
		'ti' => "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB7", // 🇪🇷 Eritreia
		'tk' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xB2", // 🇹🇲 Turcomenistão
		'tn' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xBC", // 🇧🇼 Botsuana
		'to' => "\xF0\x9F\x87\xB9\xF0\x9F\x87\xB4", // 🇹🇴 Tonga
		'ts' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'tt' => "\xF0\x9F\x87\xB7\xF0\x9F\x87\xBA", // 🇷🇺 Rússia (Tartaristão)
		'tw' => "\xF0\x9F\x87\xAC\xF0\x9F\x87\xAD", // 🇬🇭 Gana
		'ty' => "\xF0\x9F\x87\xB5\xF0\x9F\x87\xAB", // 🇵🇫 Polinésia Francesa
		'ug' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB3", // 🇨🇳 China (Xinjiang)
		've' => "\xF0\x9F\x87\xBF\xF0\x9F\x87\xA6", // 🇿🇦 África do Sul
		'vo' => "\xF0\x9F\x8C\x90",                   // 🌐 Global
		'wa' => "\xF0\x9F\x87\xA7\xF0\x9F\x87\xAA", // 🇧🇪 Bélgica (Valônia)
		'wo' => "\xF0\x9F\x87\xB8\xF0\x9F\x87\xB3", // 🇸🇳 Senegal
		'yi' => "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB1", // 🇮🇱 Israel
		'za' => "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB3", // 🇨🇳 China (Guangxi)
	);

	return isset( $flags[ $lang_code ] ) ? $flags[ $lang_code ] : "\xF0\x9F\x8C\x90";
}

/**
 * Converte nome de idioma (português, inglês ou nativo) para código ISO 639-1.
 * Cobertura completa: todos os 183 idiomas com nomes em português, inglês e nativo.
 * Ex: 'português' => 'pt', 'english' => 'en', 'deutsch' => 'de'
 */
function alvobot_get_language_iso_code( $language_name ) {
	$iso_codes = array(
		// Português => código
		'português'           => 'pt',
		'inglês'              => 'en',
		'espanhol'            => 'es',
		'francês'             => 'fr',
		'alemão'              => 'de',
		'italiano'            => 'it',
		'holandês'            => 'nl',
		'japonês'             => 'ja',
		'chinês'              => 'zh',
		'coreano'             => 'ko',
		'russo'               => 'ru',
		'árabe'               => 'ar',
		'hindi'               => 'hi',
		'turco'               => 'tr',
		'polonês'             => 'pl',
		'sueco'               => 'sv',
		'dinamarquês'         => 'da',
		'norueguês bokmål'    => 'nb',
		'finlandês'           => 'fi',
		'grego'               => 'el',
		'tcheco'              => 'cs',
		'romeno'              => 'ro',
		'húngaro'             => 'hu',
		'tailandês'           => 'th',
		'vietnamita'          => 'vi',
		'indonésio'           => 'id',
		'malaio'              => 'ms',
		'hebraico'            => 'he',
		'ucraniano'           => 'uk',
		'búlgaro'             => 'bg',
		'croata'              => 'hr',
		'eslovaco'            => 'sk',
		'esloveno'            => 'sl',
		'estoniano'           => 'et',
		'letão'               => 'lv',
		'lituano'             => 'lt',
		'sérvio'              => 'sr',
		'bósnio'              => 'bs',
		'albanês'             => 'sq',
		'macedônio'           => 'mk',
		'georgiano'           => 'ka',
		'armênio'             => 'hy',
		'azerbaijano'         => 'az',
		'cazaque'             => 'kk',
		'uzbeque'             => 'uz',
		'persa'               => 'fa',
		'urdu'                => 'ur',
		'bengali'             => 'bn',
		'tâmil'               => 'ta',
		'telugu'              => 'te',
		'malaiala'            => 'ml',
		'canarês'             => 'kn',
		'marata'              => 'mr',
		'guzerate'            => 'gu',
		'panjabi'             => 'pa',
		'nepalês'             => 'ne',
		'cingalês'            => 'si',
		'birmanês'            => 'my',
		'khmer'               => 'km',
		'laosiano'            => 'lo',
		'mongol'              => 'mn',
		'suaíli'              => 'sw',
		'amárico'             => 'am',
		'iorubá'              => 'yo',
		'igbo'                => 'ig',
		'hauçá'               => 'ha',
		'zulu'                => 'zu',
		'xhosa'               => 'xh',
		'africâner'           => 'af',
		'tagalo'              => 'tl',
		'maltês'              => 'mt',
		'islandês'            => 'is',
		'irlandês'            => 'ga',
		'galês'               => 'cy',
		'galego'              => 'gl',
		'catalão'             => 'ca',
		'basco'               => 'eu',
		'latim'               => 'la',
		'esperanto'           => 'eo',
		'guarani'             => 'gn',
		'quíchua'             => 'qu',
		'aimará'              => 'ay',
		'afar'                => 'aa',
		'abecásio'            => 'ab',
		'avéstico'            => 'ae',
		'akan'                => 'ak',
		'aragonês'            => 'an',
		'assamês'             => 'as',
		'avar'                => 'av',
		'bashkir'             => 'ba',
		'bielorrusso'         => 'be',
		'bislama'             => 'bi',
		'bambara'             => 'bm',
		'tibetano'            => 'bo',
		'bretão'              => 'br',
		'checheno'            => 'ce',
		'chamorro'            => 'ch',
		'corso'               => 'co',
		'cree'                => 'cr',
		'eslavo eclesiástico' => 'cu',
		'chuvash'             => 'cv',
		'divehi'              => 'dv',
		'dzonga'              => 'dz',
		'ewe'                 => 'ee',
		'fula'                => 'ff',
		'fijiano'             => 'fj',
		'feroês'              => 'fo',
		'frísio ocidental'    => 'fy',
		'gaélico escocês'     => 'gd',
		'manx'                => 'gv',
		'hiri motu'           => 'ho',
		'haitiano'            => 'ht',
		'herero'              => 'hz',
		'interlíngua'         => 'ia',
		'interlíngue'         => 'ie',
		'yi de sichuan'       => 'ii',
		'inupiaque'           => 'ik',
		'ido'                 => 'io',
		'inuktitut'           => 'iu',
		'javanês'             => 'jv',
		'congolês'            => 'kg',
		'quicuio'             => 'ki',
		'cuanhama'            => 'kj',
		'groenlandês'         => 'kl',
		'canúri'              => 'kr',
		'caxemira'            => 'ks',
		'curdo'               => 'ku',
		'komi'                => 'kv',
		'córnico'             => 'kw',
		'quirguiz'            => 'ky',
		'luxemburguês'        => 'lb',
		'luganda'             => 'lg',
		'limburguês'          => 'li',
		'lingala'             => 'ln',
		'luba-catanga'        => 'lu',
		'malgaxe'             => 'mg',
		'marshalês'           => 'mh',
		'maori'               => 'mi',
		'nauruano'            => 'na',
		'ndebele do norte'    => 'nd',
		'ndonga'              => 'ng',
		'norueguês nynorsk'   => 'nn',
		'norueguês'           => 'no',
		'ndebele do sul'      => 'nr',
		'navajo'              => 'nv',
		'chichewa'            => 'ny',
		'occitano'            => 'oc',
		'ojibwa'              => 'oj',
		'oromo'               => 'om',
		'oriá'                => 'or',
		'osseta'              => 'os',
		'páli'                => 'pi',
		'pashto'              => 'ps',
		'romanche'            => 'rm',
		'rundi'               => 'rn',
		'ruanda'              => 'rw',
		'sânscrito'           => 'sa',
		'sardo'               => 'sc',
		'sindi'               => 'sd',
		'sami do norte'       => 'se',
		'sango'               => 'sg',
		'samoano'             => 'sm',
		'shona'               => 'sn',
		'somali'              => 'so',
		'suázi'               => 'ss',
		'soto do sul'         => 'st',
		'sundanês'            => 'su',
		'tadjique'            => 'tg',
		'tigrínia'            => 'ti',
		'turcomano'           => 'tk',
		'tswana'              => 'tn',
		'tonganês'            => 'to',
		'tsonga'              => 'ts',
		'tártaro'             => 'tt',
		'twi'                 => 'tw',
		'taitiano'            => 'ty',
		'uigur'               => 'ug',
		'venda'               => 've',
		'volapuque'           => 'vo',
		'valão'               => 'wa',
		'uolofe'              => 'wo',
		'iídiche'             => 'yi',
		'zhuang'              => 'za',

		// English => código
		'portuguese'          => 'pt',
		'english'             => 'en',
		'spanish'             => 'es',
		'french'              => 'fr',
		'german'              => 'de',
		'italian'             => 'it',
		'dutch'               => 'nl',
		'japanese'            => 'ja',
		'chinese'             => 'zh',
		'korean'              => 'ko',
		'russian'             => 'ru',
		'arabic'              => 'ar',
		'turkish'             => 'tr',
		'polish'              => 'pl',
		'swedish'             => 'sv',
		'danish'              => 'da',
		'norwegian bokmål'    => 'nb',
		'norwegian bokmal'    => 'nb',
		'finnish'             => 'fi',
		'greek'               => 'el',
		'czech'               => 'cs',
		'romanian'            => 'ro',
		'hungarian'           => 'hu',
		'thai'                => 'th',
		'vietnamese'          => 'vi',
		'indonesian'          => 'id',
		'malay'               => 'ms',
		'hebrew'              => 'he',
		'ukrainian'           => 'uk',
		'bulgarian'           => 'bg',
		'croatian'            => 'hr',
		'slovak'              => 'sk',
		'slovenian'           => 'sl',
		'estonian'            => 'et',
		'latvian'             => 'lv',
		'lithuanian'          => 'lt',
		'serbian'             => 'sr',
		'bosnian'             => 'bs',
		'albanian'            => 'sq',
		'macedonian'          => 'mk',
		'georgian'            => 'ka',
		'armenian'            => 'hy',
		'azerbaijani'         => 'az',
		'kazakh'              => 'kk',
		'uzbek'               => 'uz',
		'persian'             => 'fa',
		'bengali'             => 'bn',
		'tamil'               => 'ta',
		'malayalam'           => 'ml',
		'kannada'             => 'kn',
		'marathi'             => 'mr',
		'gujarati'            => 'gu',
		'punjabi'             => 'pa',
		'nepali'              => 'ne',
		'sinhala'             => 'si',
		'burmese'             => 'my',
		'cambodian'           => 'km',
		'lao'                 => 'lo',
		'mongolian'           => 'mn',
		'swahili'             => 'sw',
		'amharic'             => 'am',
		'yoruba'              => 'yo',
		'hausa'               => 'ha',
		'afrikaans'           => 'af',
		'tagalog'             => 'tl',
		'filipino'            => 'tl',
		'maltese'             => 'mt',
		'icelandic'           => 'is',
		'irish'               => 'ga',
		'welsh'               => 'cy',
		'galician'            => 'gl',
		'catalan'             => 'ca',
		'basque'              => 'eu',
		'latin'               => 'la',
		'guarani'             => 'gn',
		'quechua'             => 'qu',
		'aymara'              => 'ay',
		'afar'                => 'aa',
		'abkhazian'           => 'ab',
		'avestan'             => 'ae',
		'aragonese'           => 'an',
		'assamese'            => 'as',
		'avaric'              => 'av',
		'belarusian'          => 'be',
		'bambara'             => 'bm',
		'tibetan'             => 'bo',
		'breton'              => 'br',
		'chechen'             => 'ce',
		'chamorro'            => 'ch',
		'corsican'            => 'co',
		'church slavic'       => 'cu',
		'chuvash'             => 'cv',
		'dzongkha'            => 'dz',
		'fulah'               => 'ff',
		'fijian'              => 'fj',
		'faroese'             => 'fo',
		'western frisian'     => 'fy',
		'scottish gaelic'     => 'gd',
		'haitian'             => 'ht',
		'interlingua'         => 'ia',
		'interlingue'         => 'ie',
		'sichuan yi'          => 'ii',
		'inupiaq'             => 'ik',
		'javanese'            => 'jv',
		'kongo'               => 'kg',
		'kikuyu'              => 'ki',
		'kuanyama'            => 'kj',
		'kalaallisut'         => 'kl',
		'greenlandic'         => 'kl',
		'kanuri'              => 'kr',
		'kashmiri'            => 'ks',
		'kurdish'             => 'ku',
		'cornish'             => 'kw',
		'kirghiz'             => 'ky',
		'luxembourgish'       => 'lb',
		'ganda'               => 'lg',
		'limburgish'          => 'li',
		'lingala'             => 'ln',
		'luba-katanga'        => 'lu',
		'malagasy'            => 'mg',
		'marshallese'         => 'mh',
		'northern ndebele'    => 'nd',
		'ndonga'              => 'ng',
		'norwegian nynorsk'   => 'nn',
		'norwegian'           => 'no',
		'southern ndebele'    => 'nr',
		'navajo'              => 'nv',
		'chichewa'            => 'ny',
		'occitan'             => 'oc',
		'ojibwe'              => 'oj',
		'oromo'               => 'om',
		'oriya'               => 'or',
		'ossetian'            => 'os',
		'pali'                => 'pi',
		'pashto'              => 'ps',
		'romansh'             => 'rm',
		'kirundi'             => 'rn',
		'kinyarwanda'         => 'rw',
		'sanskrit'            => 'sa',
		'sardinian'           => 'sc',
		'sindhi'              => 'sd',
		'northern sami'       => 'se',
		'sango'               => 'sg',
		'samoan'              => 'sm',
		'shona'               => 'sn',
		'somali'              => 'so',
		'swazi'               => 'ss',
		'southern sotho'      => 'st',
		'sundanese'           => 'su',
		'tajik'               => 'tg',
		'tigrinya'            => 'ti',
		'turkmen'             => 'tk',
		'tswana'              => 'tn',
		'tongan'              => 'to',
		'tsonga'              => 'ts',
		'tatar'               => 'tt',
		'tahitian'            => 'ty',
		'uyghur'              => 'ug',
		'volapük'             => 'vo',
		'walloon'             => 'wa',
		'wolof'               => 'wo',
		'yiddish'             => 'yi',

		// Nativo => código
		'español'             => 'es',
		'français'            => 'fr',
		'deutsch'             => 'de',
		'nederlands'           => 'nl',
		'svenska'             => 'sv',
		'dansk'               => 'da',
		'norsk bokmål'        => 'nb',
		'norsk bokmal'        => 'nb',
		'suomi'               => 'fi',
		'čeština'             => 'cs',
		'română'              => 'ro',
		'magyar'              => 'hu',
		'bahasa indonesia'    => 'id',
		'bahasa melayu'       => 'ms',
		'hrvatski'            => 'hr',
		'slovenčina'          => 'sk',
		'slovenščina'         => 'sl',
		'eesti'               => 'et',
		'lietuvių'            => 'lt',
		'bosanski'            => 'bs',
		'shqip'               => 'sq',
		'türkçe'              => 'tr',
		'polski'              => 'pl',
		'kiswahili'           => 'sw',
		'malti'               => 'mt',
		'íslenska'            => 'is',
		'gaeilge'             => 'ga',
		'cymraeg'             => 'cy',
		'català'              => 'ca',
		'euskara'             => 'eu',
		'brezhoneg'           => 'br',
		'corsu'               => 'co',
		'kernewek'            => 'kw',
		'gàidhlig'            => 'gd',
		'occitan'             => 'oc',
		'rumantsch'           => 'rm',
		'lëtzebuergesch'      => 'lb',
		'frysk'               => 'fy',
		'føroyskt'            => 'fo',
		'norsk nynorsk'       => 'nn',
		'norsk'               => 'no',
	);

	$lang_key = mb_strtolower( trim( $language_name ) );
	return isset( $iso_codes[ $lang_key ] ) ? $iso_codes[ $lang_key ] : '';
}
